---
layout: docs
title: What is Fontist?
html-class: overview
---
:page-liquid:

= What is Fontist?

Fontist is a simple library to find and download fonts for Windows, Linux and
Mac.

It uses a formula repository to find where to download a requested font. The
main formula repository contains a lot of fonts, including Google Fonts, SIL
Fonts, and macOS add-on fonts.

== Why use Fontist when there are other ways to install fonts?

In general, fonts can be downloaded manually and placed in a system folder.
Some fonts are even pre-installed with an OS. But fontist allows to install
fonts programmatically and consistently on all platforms (Windows, macOS, and
Linux): missing fonts would be installed, existing ones would be found and
their paths returned.

=== Install font

E.g., the following command would find where to download and install the Arial
font:

[source,sh]
----
fontist install "arial"
----

=== Install a bunch of fonts

It also allows to install several fonts with a single command.

Image you have a file:

[source,yaml]
----
# manifest.yml
---
Times New Roman:
Arial:
Courier New:
----

Then running:

[source,sh]
----
fontist manifest-install manifest.yml
----

Would install or find all 3 fonts, and return its paths.

=== Use Ruby to install fonts

Also Fontist allows to use its Ruby interface. The former tasks can be done with:

[source,ruby]
----
Fontist::Font.install("arial")
----

[source,ruby]
----
Fontist::Manifest::Install.from_file("manifest.yml")
----
