title: Fontist
description: Cross-platform font installer for Windows, Linux and macOS
# The above two are used by jekyll-seo-tag for things such as
# `<title>` and `<meta>` tags, as well as elsewhere by the theme.

permalink: /blog/:year-:month-:day-:title/

url: https://www.fontist.org
github_repo_url: https://github.com/fontist/fontist.org
github_repo_branch: main

algolia_search:
  api_key: '31ca4bad475130bdaee582a0b9f40806'
  index_name: 'fontist'

tagline: >-
  Cross-platform font installer for
  Windows, Linux and macOS

landing_priority: [custom_intro, blog, specs, software]

theme: jekyll-theme-open-project

author:
  name: Ribose Inc.
  url: https://www.ribose.com

authors:
  - name: Ribose Inc.
    email: open.source@ribose.com

contact_email: open.source@ribose.com

theme: jekyll-theme-open-project

parent_hub:
  git_repo_url: https://github.com/riboseinc/open.ribose.com
  git_repo_branch: main
  home_url: https://open.ribose.com/

includes_dir: '.'

social:
  links:
    - https://twitter.com/RiboseUS
    - https://github.com/fontist/fontist

legal:
  name: Ribose Group Inc.
  tos_link: https://www.ribose.com/tos
  privacy_policy_link: https://www.ribose.com/privacy

home_calls_to_action:
  - { url: "/software/fontist/docs/README/", title: "Using the gem" }
  #- { url: "/software/fontist-cli/docs/README/", title: "Using the CLI" }

collections:
  projects:
    output: false
  software:
    output: true
    permalink: /software/:path/
  specs:
    output: true
    permalink: /specs/:path/
  posts:
    output: true
    permalink: /blog/:year-:month-:day-:title/
  pages:
    output: true
    permalink: /:name/


defaults:
  # Theme defaults.
  # MUST be duplicated from theme’s _config.yml
  # (does not get inherited, unlike the collections hash)
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
  - scope:
      path: _software
      type: software
    values:
      layout: product
  - scope:
      path: _specs
      type: specs
    values:
      layout: spec

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

tag_namespaces:
  software:
    writtenin: "Written in"
    bindingsfor: "Bindings for"
    user: "Target user"
    interface: "Interface"
  specs:
    audience: "Audience"
    completion_status: "Status"

exclude:
  - .git
  - .lycheeignore
  - "*/.git"
  - Gemfile*
  - Makefile
  - Rakefile
  - README.adoc
  - vendor # for deployment
