/**
 * Canonical home for domain entity types.
 * See TODO.unify/08-domain-model.md for the target entity model.
 */

// ---------- Formula (current shape; will split per 08-domain-model.md) ----------

export interface FormulaData {
  name: string
  formulaName: string
  slug: string
  familyCount: number
  styleCount: number
  familyNames: string[]
  sourceType: string
  platforms: string[]
  licenseType: string
  licenseCategory: string
  licenseName: string
}

// ---------- FormulaDetails (rich detail from archive-private write_details) ----------
// Mirrors the formula YAML's identity fields, dropping heavy license text and
// internal directives. Generated by fontist-archive-private/bin/build; copied
// to archive-public; fetched by scripts/fetch-data.sh. The formula YAML is the
// authoritative source for font family/style identity (see coverage-architecture.md
// Domain Model). Schema: TODO.formulas/01-details-schema.md.

export interface FormulaDetailsResource {
  source?: string
  family?: string
  urls?: string[]
  files?: string[]
  format?: string
}

export interface FormulaDetailsStyle {
  family_name: string
  type: string
  full_name?: string
  post_script_name?: string
  version?: string
  copyright?: string
  description?: string
  variable_font?: boolean
  font?: string
  formats?: string[]
  font_index?: number
}

export interface FormulaDetailsFont {
  name: string
  styles: FormulaDetailsStyle[]
}

export interface FormulaDetailsCollection {
  filename: string
  fonts: FormulaDetailsFont[]
}

export interface FormulaDetails {
  slug: string
  name: string
  description?: string
  homepage?: string
  copyright?: string
  spdx_license?: string
  license_url?: string
  redistributable: boolean
  source_format?: string
  resources?: Record<string, FormulaDetailsResource>
  fonts: FormulaDetailsFont[]
  font_collections?: FormulaDetailsCollection[]
}

// ---------- Font ----------

export interface FontEntry {
  canonical_name: string
  slug: string
  formulas: string[]
  style_count: number
}

export interface FontMetadataEntry {
  slug: string
  formula_path: string
  redistributable: boolean
  primary_family: string | null
  coverage_file: string
  woff_file: string
}

export interface FontsRegistry {
  generated_at: string
  total_fonts: number
  total_formulas: number
  fonts: FontEntry[]
}

export interface FontMetadataFile {
  generated_at: string
  total_fonts: number
  redistributable: number
  fonts: FontMetadataEntry[]
}

// ---------- FontFamily (entity introduced per TODO.unify/13 + TODO.unify/14) ----------
// A FontFamily is the canonical typographic entity: one named family
// (e.g. "Roboto", "Abyssinica SIL") addressable at /families/:familySlug.
// Multiple Formulas can provide the same family; `formula_slugs[]` is the
// reverse index that lets the page render provenance without re-scanning
// every formula. Generated by scripts/gen-font-families.mjs into
// public/font-families.json.

export interface FontFamilyFile {
  slug: string
  // PostScript name — the face's unique key within its formula. slug is NOT
  // unique (distinct faces can slugify identically), so identity is (ps,
  // formula_slug).
  ps: string
  formula_slug: string
  style: string
  path: string | null
  coverage_file: string | null
  redistributable: boolean
  version: string | null
  font_revision: number | null
}

export interface FontFamily {
  slug: string
  name: string
  formula_slugs: string[]
  style_count: number
  redistributable: boolean
  license_name: string
  files: FontFamilyFile[]
}

export interface FontFamilyIndex {
  generated_at: string
  total_families: number
  families: FontFamily[]
}

// ---------- Markdown ----------

export interface Frontmatter {
  title?: string
  description?: string
  date?: string
  authors?: string[]
}

export interface ParsedMarkdown {
  raw: string
  frontmatter: Frontmatter
  body: string
}

// ---------- Font rendering context ----------
// Lives in the fonts domain (not lib/unicode/types) because it carries font
// identity + a coverage set. The unicode grid component accepts it as a prop
// (rendering concern), which is why the dependency direction is fonts → unicode,
// not the reverse.

export interface FontContext {
  slug: string
  familyName: string
  fontId: string
  fontPath: string | null
  redistributable: boolean
  coverage: Set<number>
  color: string
}

// ---------- Coverage (was `any` in useCoverage.ts — AUDIT C.3) ----------
// Shape pinned to actual fontist-archive output (scripts/fetch-data.sh).
// `blocks`, `variable_axes`, `opentype_features`, `total_blocks` are
// optional — non-variable fonts (the common case) omit them.

export interface CoverageBlock {
  name: string
  range: string
  start: number
  end: number
  codepoints: number[]
}

export interface CoverageVariableAxis {
  tag: string
  name: string
  min: number
  default: number
  max: number
}

export interface CoverageFeature {
  tag: string
  name: string
}

export interface CoveragePlanes {
  bmp: boolean
  smp: boolean
  sip: boolean
}

export interface Coverage {
  slug: string
  redistributable: boolean
  total_codepoints: number
  supported_blocks: number
  total_blocks?: number
  planes: CoveragePlanes
  codepoints: number[]
  blocks?: CoverageBlock[]
  variable_axes?: CoverageVariableAxis[]
  opentype_features?: CoverageFeature[]
}

// ---------- Codepoint detail (per-codepoint JSON from ucode) ----------
// Emitted by ucode's per-codepoint exporter; lives at
// /codepoints/{lowercase-hex-zero-padded-to-4}.json. The filename
// contract (lowercase hex, zero-padded to 4, no `U+` prefix) is the
// canonical form used by `hexCp()` and `loadCodepointDetail()`.
// Sample shape verified against public/codepoints/20ac.json.

export interface CodepointBidi {
  class: string
  is_mirrored: boolean
}

export interface CodepointDisplay {
  east_asian_width?: string
  line_break_class?: string
  vertical_orientation?: string
}

export interface CodepointBreakSegmentation {
  grapheme?: string
  word?: string
  sentence?: string
}

export interface CodepointIndic {
  positional_category?: string
  syllabic_category?: string
}

export interface CodepointHangul {
  type?: string
  jamo_short_name?: string
}

export interface CodepointEmoji {
  is_emoji?: boolean
  is_extended_pictographic?: boolean
  is_presentation_default?: boolean
  is_modifier?: boolean
  is_base?: boolean
  is_component?: boolean
}

export interface UnihanField {
  name: string
  values: string[]
}

export interface CodepointUnihan {
  dictionary_indices?: UnihanField[]
  readings?: UnihanField[]
  variants?: UnihanField[]
  numeric_values?: UnihanField[]
  radical_stroke_counts?: UnihanField[]
  dictionary_like_data?: UnihanField[]
  irg_sources?: UnihanField[]
  other_mappings?: UnihanField[]
}

export interface CodepointDetail {
  codepoint: number
  id: string
  name: string
  block_id: string
  plane_number: number
  script_code: string
  age: string
  general_category: string
  combining_class: number
  bidi: CodepointBidi
  display?: CodepointDisplay
  break_segmentation?: CodepointBreakSegmentation
  indic?: CodepointIndic
  hangul?: CodepointHangul
  emoji?: CodepointEmoji
  binary_properties?: string[]
  unihan?: CodepointUnihan
}
